# Generated by Django 4.2.5 on 2023-10-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_nutrition', '0002_product_existence_delete_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
    ]
