# Generated by Django 4.2.5 on 2023-11-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_nutrition', '0003_cart_for_anonymous_user_cart_in_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
    ]
